{
  config,
  lib,
  pkgs,
  ...
}:
let
  scrinio = pkgs.callPackage ../../pkgs/scrinio.nix { };
  helium-browser = pkgs.callPackage ../../pkgs/helium-browser.nix { };
in
{
  options.userPackages.enable = lib.mkEnableOption "Enable user packages";

  config = lib.mkIf config.userPackages.enable {
    home.packages = with pkgs; [
      act
      xmodmap
      ani-cli
      aseprite
      xrandr
      b3sum
      bitcoind
      biome
      brave
      blender
      browsh
      bun
      burpsuite
      cargo-edit
      cargo-generate
      cargo-msrv
      cargo-update
      claude-code
      cmake
      deno
      dig
      discord
      dua
      firefox-devedition
      fish
      font-manager
      gimp
      godot
      gopls
      github-cli
      gpu-screen-recorder
      grim
      harper
      helium-browser
      heroic
      hydra-check
      imagemagick
      inkscape
      insomnia
      just-formatter
      just-lsp
      keepassxc
      libnotify
      lua-language-server
      mdbook
      nixd
      nixfmt
      nix-index
      nodejs_latest
      ollama-cuda
      opencode
      pnpm
      qbittorrent
      racket
      rclone
      rofi
      rustup
      rust-code-analysis
      scrinio
      semgrep
      signal-desktop
      slack
      slurp
      steel
      stylua
      svelte-language-server
      swaybg
      telegram-desktop
      tiled
      tridactyl-native
      typescript
      typescript-language-server
      typst
      typstyle
      typst-live
      tailwindcss-language-server
      tree-sitter
      tombi
      # upwork
      uv
      wayvnc
      wezterm
      wiremix
      vscode-langservers-extracted
      xwayland-satellite
      wireshark
      yt-dlp
      zathura
      zed-editor
      zoxide
      zls
      vscode-langservers-extracted
      sccache
    ];
  };
}
